/* Product catalog for Central Asia Harvest
   Each product has stylized fill color (matching real color)
   used for the silhouette/blob in the placeholder card. */

window.CATEGORIES = [
  { id: 'all',     ru: 'Все',         en: 'All' },
  { id: 'fruits',  ru: 'Фрукты',      en: 'Fresh Fruits' },
  { id: 'veg',     ru: 'Овощи',       en: 'Vegetables' },
  { id: 'legumes', ru: 'Бобовые',     en: 'Legumes' },
  { id: 'dried',   ru: 'Сухофрукты',  en: 'Dried & Nuts' },
  { id: 'melons',  ru: 'Бахчевые',    en: 'Melons & Gourds' },
];

window.PRODUCTS = [
  // FRUITS
  { id: 'pomegranate', cat: 'fruits', name: 'Гранат', variety: 'Кызыл-анар, Узбекистан',
    price: 1.4, unit: 'кг', tag: 'СЕЗОН', tagKind: 'pom', color: '#A23A2B', shape: 'sphere',
    season: 'Окт–Дек', moq: 'от 20 т' },
  { id: 'apricot', cat: 'fruits', name: 'Абрикос', variety: 'Хурмаи, Субхони',
    price: 1.8, unit: 'кг', tag: 'ЛЮКС', tagKind: 'gold', color: '#E89A47', shape: 'sphere',
    season: 'Май–Июль', moq: 'от 18 т' },
  { id: 'grapes', cat: 'fruits', name: 'Виноград', variety: 'Хусайни, Дамские пальчики',
    price: 1.6, unit: 'кг', color: '#5B7A2F', shape: 'cluster',
    season: 'Авг–Окт', moq: 'от 20 т' },
  { id: 'cherry', cat: 'fruits', name: 'Черешня', variety: 'Ферганская розовая',
    price: 2.4, unit: 'кг', tag: 'СЕЗОН', tagKind: 'pom', color: '#8A1F2A', shape: 'cluster',
    season: 'Май–Июнь', moq: 'от 12 т' },
  { id: 'peach', cat: 'fruits', name: 'Персик', variety: 'Ферганский, Самаркандский',
    price: 1.5, unit: 'кг', color: '#E58B5E', shape: 'sphere',
    season: 'Июнь–Сент', moq: 'от 20 т' },
  { id: 'persimmon', cat: 'fruits', name: 'Хурма', variety: 'Королёк, Шарон',
    price: 1.7, unit: 'кг', tag: 'ЛЮКС', tagKind: 'gold', color: '#D67A2C', shape: 'sphere',
    season: 'Окт–Дек', moq: 'от 20 т' },
  { id: 'apple', cat: 'fruits', name: 'Яблоки', variety: 'Айдаред, Голден',
    price: 0.9, unit: 'кг', color: '#C9302A', shape: 'sphere',
    season: 'Авг–Май', moq: 'от 22 т' },
  { id: 'quince', cat: 'fruits', name: 'Айва', variety: 'Анжерская, Исфаганская',
    price: 1.3, unit: 'кг', color: '#E0B23A', shape: 'sphere',
    season: 'Сент–Дек', moq: 'от 20 т' },

  // VEGETABLES
  { id: 'tomato', cat: 'veg', name: 'Помидоры', variety: 'Бычье сердце, Андижан',
    price: 0.95, unit: 'кг', tag: 'ЛЮКС', tagKind: 'gold', color: '#C9302A', shape: 'sphere',
    season: 'Круглый год', moq: 'от 22 т' },
  { id: 'onion', cat: 'veg', name: 'Лук', variety: 'Сладкий жёлтый',
    price: 0.55, unit: 'кг', color: '#D4A958', shape: 'sphere',
    season: 'Круглый год', moq: 'от 22 т' },
  { id: 'carrot', cat: 'veg', name: 'Морковь', variety: 'Мирзойи, Шантане',
    price: 0.6, unit: 'кг', color: '#D17A3A', shape: 'long',
    season: 'Круглый год', moq: 'от 22 т' },
  { id: 'cucumber', cat: 'veg', name: 'Огурцы', variety: 'Парниковые',
    price: 1.1, unit: 'кг', color: '#3F6B2A', shape: 'long',
    season: 'Круглый год', moq: 'от 18 т' },
  { id: 'pepper', cat: 'veg', name: 'Перец болгарский', variety: 'Калифорнийское чудо',
    price: 1.3, unit: 'кг', color: '#C9302A', shape: 'bell',
    season: 'Июль–Ноя', moq: 'от 18 т' },
  { id: 'garlic', cat: 'veg', name: 'Чеснок', variety: 'Андижанский',
    price: 2.1, unit: 'кг', tag: 'ЭКСПОРТ', tagKind: '', color: '#EDE3CC', shape: 'sphere',
    season: 'Круглый год', moq: 'от 18 т' },

  // LEGUMES
  { id: 'mungbean', cat: 'legumes', name: 'Маш', variety: 'Зелёный, очищенный',
    price: 1.3, unit: 'кг', tag: 'ХИТ', tagKind: 'pom', color: '#5B7A2F', shape: 'grain',
    season: 'Круглый год', moq: 'от 24 т' },
  { id: 'chickpea', cat: 'legumes', name: 'Нут', variety: 'Бомбейский, кабули',
    price: 1.4, unit: 'кг', color: '#D4A04A', shape: 'grain',
    season: 'Круглый год', moq: 'от 24 т' },
  { id: 'lentil', cat: 'legumes', name: 'Чечевица', variety: 'Красная, зелёная',
    price: 1.5, unit: 'кг', color: '#B8553A', shape: 'grain',
    season: 'Круглый год', moq: 'от 24 т' },
  { id: 'kidney', cat: 'legumes', name: 'Фасоль', variety: 'Лоббиё, белая',
    price: 1.2, unit: 'кг', color: '#8B2A1F', shape: 'grain',
    season: 'Круглый год', moq: 'от 24 т' },

  // DRIED FRUITS & NUTS
  { id: 'raisins', cat: 'dried', name: 'Изюм', variety: 'Сояги, Сабза, Кишмиш',
    price: 2.2, unit: 'кг', tag: 'ХИТ', tagKind: 'pom', color: '#5B3A20', shape: 'grain',
    season: 'Круглый год', moq: 'от 20 т' },
  { id: 'kuraga', cat: 'dried', name: 'Курага', variety: 'Субхони, без сернистая',
    price: 3.4, unit: 'кг', tag: 'ЛЮКС', tagKind: 'gold', color: '#D17A2C', shape: 'sphere',
    season: 'Круглый год', moq: 'от 20 т' },
  { id: 'prune', cat: 'dried', name: 'Чернослив', variety: 'Кавказский, копчёный',
    price: 2.8, unit: 'кг', color: '#2C1810', shape: 'sphere',
    season: 'Круглый год', moq: 'от 20 т' },
  { id: 'walnut', cat: 'dried', name: 'Грецкий орех', variety: 'Очищенный, светлая половина',
    price: 6.5, unit: 'кг', tag: 'ЭКСПОРТ', tagKind: '', color: '#A87844', shape: 'nut',
    season: 'Круглый год', moq: 'от 18 т' },
  { id: 'almond', cat: 'dried', name: 'Миндаль', variety: 'Бухарский, очищенный',
    price: 8.4, unit: 'кг', color: '#D4A878', shape: 'nut',
    season: 'Круглый год', moq: 'от 18 т' },
  { id: 'pistachio', cat: 'dried', name: 'Фисташка', variety: 'Бостанлык, обжаренная',
    price: 11.2, unit: 'кг', tag: 'ЛЮКС', tagKind: 'gold', color: '#7A8A3A', shape: 'nut',
    season: 'Круглый год', moq: 'от 14 т' },

  // MELONS
  { id: 'mirzachul', cat: 'melons', name: 'Дыня Мирзачульская', variety: 'Гуляби, медовая',
    price: 0.9, unit: 'кг', tag: 'ЛЮКС', tagKind: 'gold', color: '#E0B848', shape: 'oval',
    season: 'Авг–Окт', moq: 'от 22 т' },
  { id: 'watermelon', cat: 'melons', name: 'Арбуз', variety: 'Хорезмский, без косточек',
    price: 0.45, unit: 'кг', color: '#2A6F2A', shape: 'oval',
    season: 'Июль–Сент', moq: 'от 22 т' },
  { id: 'gulabi', cat: 'melons', name: 'Дыня Гуляби', variety: 'Поздняя, длинного хранения',
    price: 1.1, unit: 'кг', color: '#D4A858', shape: 'oval',
    season: 'Сент–Янв', moq: 'от 22 т' },
  { id: 'pumpkin', cat: 'melons', name: 'Тыква', variety: 'Мускатная узбекская',
    price: 0.55, unit: 'кг', color: '#D17A2C', shape: 'oval',
    season: 'Сент–Фев', moq: 'от 20 т' },
];
